services:
  appointment_scheduler_razor:
    image: appointment_scheduler_razor
    build:
      context: .
      dockerfile: AppointmentSchedulerRazor/Dockerfile
    depends_on:
      - db
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres