services:
  appointment_scheduler_razor:
    image: appointment_scheduler_razor
    build:
      context: .
      dockerfile: AppointmentSchedulerRazor/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: production
    depends_on:
      - db
    ports:
      - 8080:8080
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres